// AUTO-GENERATED FILE — DO NOT EDIT MANUALLY.
//
// This file is regenerated by running:
//     dart run tool/sync_version.dart
//
// The SINGLE SOURCE OF TRUTH for the version is pubspec.yaml.
// Change the version there, then run the command above (or push — CI does it).

/// Application version constants, always in sync with pubspec.yaml.
class AppVersion {
  AppVersion._();

  /// Semantic version string (e.g. "1.2.6").  Matches the GitHub release tag.
  static const String current = '1.2.6';

  /// Build number — the +N suffix from pubspec.yaml.
  static const int buildNumber = 1;

  /// Full version string including build number (e.g. "1.2.6+1").
  static const String full = '1.2.6+1';
}
