// tool/sync_version.dart
//
// Reads the version from pubspec.yaml and regenerates
// lib/constants/app_version.dart so Dart code always reflects pubspec.yaml.
//
// Usage:
//   dart run tool/sync_version.dart
//
// Run this after every change to the `version:` field in pubspec.yaml,
// or let the CI workflow and git pre-commit hook do it automatically.

import 'dart:io';

void main(List<String> args) {
  final root = _projectRoot();

  // ── 1. Read pubspec.yaml ──────────────────────────────────────────────────
  final pubspecFile = File('${root.path}${Platform.pathSeparator}pubspec.yaml');
  if (!pubspecFile.existsSync()) {
    stderr.writeln('[sync_version] ERROR: pubspec.yaml not found at ${pubspecFile.path}');
    exit(1);
  }

  final pubspecLines = pubspecFile.readAsLinesSync();
  String? rawVersion;
  for (final line in pubspecLines) {
    final match = RegExp(r'^version:\s*(.+)$').firstMatch(line.trim());
    if (match != null) {
      rawVersion = match.group(1)!.trim();
      break;
    }
  }

  if (rawVersion == null) {
    stderr.writeln('[sync_version] ERROR: No "version:" field found in pubspec.yaml');
    exit(1);
  }

  // Split "1.3.0+5" -> version="1.3.0", build=5
  final parts = rawVersion.split('+');
  final semver = parts[0];
  final build = parts.length > 1 ? int.tryParse(parts[1]) ?? 1 : 1;

  // ── 2. Generate app_version.dart ─────────────────────────────────────────
  final outFile = File(
    '${root.path}${Platform.pathSeparator}'
    'lib${Platform.pathSeparator}'
    'constants${Platform.pathSeparator}'
    'app_version.dart',
  );

  // Use a StringBuffer so the template does not need escaped quotes inside the
  // here-document — avoids the `unnecessary_string_escapes` lint.
  final buf = StringBuffer()
    ..writeln('// AUTO-GENERATED FILE — DO NOT EDIT MANUALLY.')
    ..writeln('//')
    ..writeln('// This file is regenerated by running:')
    ..writeln('//     dart run tool/sync_version.dart')
    ..writeln('//')
    ..writeln('// The SINGLE SOURCE OF TRUTH for the version is pubspec.yaml.')
    ..writeln('// Change the version there, then run the command above (or push — CI does it).')
    ..writeln()
    ..writeln('/// Application version constants, always in sync with pubspec.yaml.')
    ..writeln('class AppVersion {')
    ..writeln('  AppVersion._();')
    ..writeln()
    ..writeln('  /// Semantic version string (e.g. "1.3.0").  Matches the GitHub release tag.')
    ..writeln("  static const String current = '$semver';")
    ..writeln()
    ..writeln('  /// Build number — the +N suffix from pubspec.yaml.')
    ..writeln('  static const int buildNumber = $build;')
    ..writeln()
    ..writeln('  /// Full version string including build number (e.g. "1.3.0+1").')
    ..writeln("  static const String full = '$rawVersion';")
    ..writeln('}');
  final content = buf.toString();

  outFile.parent.createSync(recursive: true);
  outFile.writeAsStringSync(content);

  stdout.writeln('[sync_version] Written: ${outFile.path}');
  stdout.writeln('[sync_version] Version: $semver  Build: $build');
}

/// Walk up from the script location until we find pubspec.yaml.
Directory _projectRoot() {
  var dir = File(Platform.script.toFilePath()).parent;
  while (!File('${dir.path}${Platform.pathSeparator}pubspec.yaml').existsSync()) {
    final parent = dir.parent;
    if (parent.path == dir.path) {
      stderr.writeln('[sync_version] ERROR: Could not locate project root (pubspec.yaml)');
      exit(1);
    }
    dir = parent;
  }
  return dir;
}
